CREATE TABLE "THING" (
 "ID" TEXT,
 "PATH1" TEXT,
 "PATH2" TEXT,
 "PATH3" TEXT,
 "PATH4" TEXT,
 "NAME" TEXT NOT NULL,
 "ALIAS" TEXT UNIQUE,
 "SINCE" TEXT,
 "PRICE_KC" TEXT,
 "NOTE" TEXT,
 PRIMARY KEY("ID")
);
