CREATE TABLE "TODO" (
 "ID" TEXT,
 "NAME" TEXT NOT NULL UNIQUE,
 "DEADLINE" TEXT,
 "LAST_REMINDED" TEXT,
 "REMINDER_TYPE" TEXT DEFAULT 'WEEKLY',
 "NOTE" TEXT,
 "DONE" INTEGER DEFAULT 0,
 PRIMARY KEY("ID")
);